version: "3.9"

name: "respect_the_pizza"

services:
  zookeeper:
    container_name: zookeeper-server
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - kafka-net

  kafka:
    container_name: kafka-server
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper-server:2181
    networks:
      - kafka-net

networks:
  kafka-net: