FROM eclipse-temurin:17-jdk

RUN mkdir /opt/hugh

COPY download/apache-zookeeper-3.8.1-bin /opt/zookeeper

WORKDIR /opt/zookeeper

COPY vol-zoo/conf/zoo.cfg conf/

EXPOSE 2181 2888 3888

CMD ["bin/zkServer.sh", "start-foreground"]